env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "TWRP CI"
  timeout_in: 120m
  container:
      image: ghcr.io/faoliveira78/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash script.sh sync

  DevDepsSync_script:
      - bash script.sh syncDevDeps

  Build_script:
      - bash script.sh build

  Upload_script:
      - bash script.sh upload
